- BasementRenovatorAfterbirth.py
This commit fixes errors on windows relating to the resource locator
function incorrectly parsing and utilizing the resource path specified;
this also should help when the steam library is in a non-default
location.
Submitting a pull request to Tempus repo.
This fixes issue #120
> Fixed errors with the resource locator on windows

- .gitignore
- BasementRenovator.py
BR uses the Qt settings system in a way that doesn't
save settings properly between runs.
This fixes it so it uses a settings.ini file to determine various
settings, including but not limited to properly saving window state and
resource paths.
This also greatly enhances path detection. (at least on windows)
Starting from your steam install directory, BR will now intelligently
try to figure out your install location, and from that your resource and
mod paths. Additionally, it will now load your most recent stb
automatically at startup and try to save/load with the dialog from your
mod directory rather than your resources folder.
Also fixes a couple of minor bugs:
- There was always the intent to overlay the default "no room loaded"
background with a white overlay, but the way it was …
> enhance settings system and path detection

- BasementRenovator.py
- README.md
BR will now scan the mods folder for additional entities. It will only
check enabled mods to reduce clutter.
It also adds the option to autogenerate entries for enabled mods from
their entities2 xml. This is not recommended, but is included for
unsupported mods.
> add mod support to BR

- BasementRenovator.py
- README.md
- resources/modtemplate/main.lua
- resources/modtemplate/metadata.xml
Hooks are a list of scripts that get called when a BR action happens.
This implements hooks for saving and starting a room test.
To go with the test hooks, the BR helper mod is now formalized and has a
lua component that has callbacks. This is the first half of
compatibility with stage api.
Improves the basement replacement test method; it now can replace
whatever floor's files are relevant. It and starting room will now also
change stage as appropriate when the game starts.
Stage Replacement tests also now force the floor to be XL, turns off
Curse of the Lost, and gives the player The Mind to make reset scumming
easier.
Instapreview now supports steam urls
Add blue womb and fix cathedral and sheol for instapreview; the ids
weren't updated after rebirth and blue womb took their old id
> add save and test hooks, BR mod callbacks, enhance test methods

- BasementRenovator.py
- NicheFeatures.md
Add ability to "recompute" room variants, which sorts them and then
renumbers them linearly starting from the first variant
Fix a bug where the editor would "hop" after replacing entities with a
room visible
Fix a small bug with door prefix sorting
> add recompute (sort + compact) room variants

- BasementRenovator.py
- NicheFeatures.md
Previously, autogen used the first frame of the first layer of the
default animation of an entity as its icon. It was suggested that it
should actually use every layer's first frame in that animation
This recreates the transformational properties that an anm2 frame can
have in more depth in order to faithfully reassemble the first frame of
animation. Note this will still not work for entities that use overlays,
or for entities with only invisible frames/layers
Also adds a helper setting, FixIconFormat, which allows users to fix
annoying libpng warnings clogging up the logs
> enhance autogen mod icon support

- BasementRenovator.py
- NicheFeatures.md
- resources/icongenerator.py
Make it so that recompute only tidies the variant numbers without
sorting. Instead, now sorting by name and by variant (superceded by
type) are separate actions to allow for more fine grained control
Tweak autogen with more logs and remove scaling from thumbnail gen
Create a separate script for generating BR icons using the
same method autogen does, but with the ability to select which animation
is used, pick frames, and specify an overlay. This allows for very easy
icon generation from game assets. Find it in resources/icongenerator.py
Tweak entities2 verification to only allow optional subtype, since
that's what the game does (seemingly)
Allow newly saved files to show up in the recent files list
Fix a bug in entity tooltips that showed the x coord as the y coord
Added missing timeout …
> tweak recompute room entities

- BasementRenovator.py
- NicheFeatures.md
Allow keeping the current entity filter when selecting a new paint
entity by holding Ctrl. The normal behavior can be inverted via the new
Pin Entity Filter setting
Fix a crash caused by a misplaced dialog title setting when clicking the
Set Hooks option
Add name verification when loaded modded entities. This compares a
simplified version of the name with the one from the entities2 xml
Small tweak to export to use the new recent folder logic
> add ability to pin entity filter

- BasementRenovator.py
Moving entities in and out of stacks and then deleting
them commonly caused crashes.
This attempts to fix that by avoiding explicit deletion.
This should truly be fixed once the proposed dialog gets coded
Also removes backspace for entity deletion to facilitate using the popup
> fix deleting previously stacked entities

- BasementRenovator.py
- resources/modtemplate/main.lua
Now the modal popup when testing can be disabled. If it is, 5 minutes
after starting a test without beginning another one the helper mod will
be disabled. It will also be unconditionally disabled upon closing
normally
The helper mod now displays on screen text to clearly indicate that it's
enabled. Also fix bug in fetching room name to test xml file
Fix some bugs in room duplication, they're now inserted in the right
place and with better ids
Fix a crash when selecting an invalid entity in a set
Add a room prefix to the log indicating invalid entities in a room file
Fix crash when opening file that does not exist
> add option to disable test dialog

- BasementRenovator.py
- resources/EntitiesAfterbirthPlus.xml
The filter for empty rooms includes "useless" entities that don't make
for very interesting rooms. This is no longer hard coded and can be
customized through the 'InEmptyRoom' attribute (set to 1)
Add this attribute to cobwebs, rocks, bomb rocks, pits, metal blocks,
decorations, carpet, dice floor, and fireplaces
Add another attribute NoBlockDoors to some entities in preparation for
another change
Fix a bug where effect entities weren't checked properly when loading br
compatible mods would not check effect entities properly
Allow mods to replace existing entities properly rather than allowing
both to semi exist to facilitate asset replacement
> allow specifying empty room ents in xml

- BasementRenovator.py
- README.md
- src/roomconvert.py
This isn't full rebirth compatibility, as it still shows all the
afterbirth ents and doesn't account for adjusted entity ids.
This would be a much bigger undertaking, (particularly requiring
and overhaul in how the data xmls are handled) and may be done later.
add fallback shape 0 code for afterbirth stbs with null rooms
> add rebirth stb compatibility

- BasementRenovator.py
- NicheFeatures.md
Launching Isaac through command line arguments for Instapreview triggers
an aggravating popup. Running it through the Steam executable directly
avoids this problem while still forwarding arguments.
To allow users with DRM free copies of Isaac (however few they may be)
to launch it normally, there's an optional override setting.
> launch test Isaac through Steam

- BasementRenovator.py
- INSTALL.md
- resources/EntitiesRepentance.xml
Allows adding additional groups or kinds to entities with a sub tag, like so:
```xml
<entity Group="Random" ID="5" Image="resources/Entities/5.90.0 - RBattery.png" Kind="Pickups" Name="Random Battery" Subtype="0" Variant="90">
<group Name="Batteries" />
</entity>
```
The group's Name will default to the entity's Group tag if not specified, and the group's Kind will default to the entity's Kind tag similarly.
Duplicate entries for the same entity still work for this purpose, but I've replaced the ones in `EntitiesRepentance.xml` with this system. I haven't gone through the older xml versions to remove duplicate entries yet.
Also forces groups named "Random" to the top of the list via hardcoding to get rid of the " Random" issue; this should probably be changed later to a more flexible …
> "group" sub-tag for entity entries allowing placing an entity in multiple groups / tabs without duplicate entries

- resources/modtemplate/metadata.xml
Using spaces allows the mod to load earlier, which is necessary to load before some mods, including StageAPI due to a recent update.
> BR Test Mod uses spaces instead of exclamation points

- BasementRenovator.py
- src/lookup.py
Adds a new type of widget usable by the entity parameters system, the bitmap. It's a collection of checkboxes that each represent one bit in the final value.
Grid width and total size of the bitmap are configurable with the Width and Length properties, e.g:
`<bitmap Name="Funky Bitmap" Length="16" Width="4"/>` creates the bitmap shown above.
> New "Bitmap" bitfield element widget type

- BasementRenovator.py
Entities with bitfields will not lose their gfx override when changing their Variant/Subtype (depending on what bitfields they have)
> Fix bitfields interfering with entity gfx overrides

- BasementRenovator.py
- README.md
- resources/EntitiesRepentance.xml
- resources/modtemplate/main.lua
Setting is labeled "Disable In-Game UI" under the Test tab. When enabled, rendered text and door sprites associated with the BR test mod will be disabled, which is ideal for when aesthetically pleasing screenshots or footage is desired.
> Add setting to disable in-game UI + add Migraine to alt Ch2 shared enemies

- .vscode/launch.json
- BasementRenovator.py
- NicheFeatures.md
- src/lookup.py
Copying the feature description from the included doc in `NicheFeatures.md`:
---
In case you have two grid entities that use pit tiling and need to tile with each other/other tiles other than themselves, you can use the `pitextra` sub-node for entities.
An example:
```xml
<entity Image="..." EditorImage="mypit.png" UsePitTiling="1" [other attributes]>
<pitextra Image="otherpit.png"></pitextra>
<pitextra Image="arbitraryGrid.png"></pitextra>
</entity>
```
In this example, the mypit.png pits will connect to tiles with the specified spritesheets (even if they do not use pit tiling themselves).
Make sure if there is a different `EditorImage` in the specified entities to use the path to that spritesheet instead of Image.
---
Usecase: this would be useful for some WIP Revelations features.
> Pit tiling with other tiles

- BasementRenovator.py
It was due to a bug with Qt5 that it allowed you replace items in the list. Implemented a workaround found here: https://forum.qt.io/post/774176
> Fix drag-and-drop allowing you to replace items in the RoomSelector list, causing a crash

- BasementRenovator.py
Replaces the existing "Set Resources Path" and "Reset Resources Path" actions with a new "Set Paths" action that opens a new window for modifying the install/mods/resources/exe path settings.
Previously, modifying the existing installation/mods paths in the gui was not possible. The ability to set (and save) a custom exe path is new, and enables support for alternative game launch methods (such as the upcoming REPENTOGON Launcher application).
Paths are greyed out if they are not customized.
> Add "Set Paths" dialog for changing the install/mods/resources/exe paths

- BasementRenovator.py
- src/lookup.py
`xmlLookups.stages.lookup(path=path)` will retrieve all stages whose "Pattern" value is present anywhere in the path string. Currently, these results are in their xml ordering. The last element in the return value is picked in most existing cases.
This can cause odd behaviour if the path happens to contain multiple valid stage names. A notable example is a linux-style path like `/home/.../basement.xml`, which will test the stage in home instead of basement, since home is later in the xml ordering.
In contrast, the decision of which stage to use for the room editor backdrop is only based on the filename, not the whole path. This leads to some inconsistencies where `/home/.../basement.xml` will show basement in the room editor but run tests in home. Additionally, a path like …
> Fix issues/inconsistencies with stage lookups
