Basement-Renovator/basement-renovator

- BasementRenovator.py
BR was using tabs, which is not recommended for python. This caused some
bugs with newer code added with spaces. This commit also corrects those
indentation problems since they didn't make it into the original commit.
Also has a couple of small code changes to fix some bug edge cases for
popups. They will never get removed now so entities with stacks will
just have them forever now until they're deleted. OH WELL.
To see these code changes better, view the files in this commit and add
`?w=1` to the github url.
> convert tabs to spaces

- BasementRenovator.py
> skip mods with bad entity xmls, add name fallback

- BasementRenovator.py
Currently BR loads the entities2 for all mods regardless of whether
autogen is on or not. This is unnecessary when it's off and the mod does
not have a BR entities xml. This change fixes that.
Also removes familiars from autogen and changes the output directory.
Also improves logging for out of bounds entities. (have had this change
locally for a while, it's minor but it helps for debugging and finding
these rooms)
> fix loading entities2 for mods without BR support

- BasementRenovator.py
- Reordered the room context menu. Changed difficulty to a spinbox.
Changed room shape to a combo box
- Tweaked the mechanism for determining which directory to pick when
opening an stb to ignore the standard stage path
- fix some stupid indentation bugs I missed that were messing with
selecting a resource path
- fix a bug when saving the entity list with no room selected
- add enhanced error feedback when testing rooms with bad paths
- move the instant preview xml into BR instead of the install folder for
cleanliness
- clean up the todo list
> various ui tweaks

- BasementRenovator.py
No intent to actively fix this issue as it should be addressed in rep,
but adds logging to make finding rooms with bad doors easier
> add logs for bad door configurations

- BasementRenovator.py
Instead of falling back properly when the install folder is invalid,
finding the mod path gave up pretty early. This fixes that.
Fix a bug that happened due to the ModTemp entities folder not
being committed to git. This just generates it when autogen is on
Fix a bug caused by a stash in the previous entity info conversion
Add an error message for when a mod entity has a duplicate id, variant,
and subtype
Add baseHP to autogenerated entities
> fix fallback logic for finding the mod path

- BasementRenovator.py
Allow mods to add new tabs to
the entity palette
Make name matching more permissive
Be more permissive for missing subtypes, and verify if the main
vairant has a name match
Include Boss and Champion info in the display
(to be added for official stuff)
Add a shortcut to recompute entities
> add custom palette tab support

- BasementRenovator.py
Allows for compatibility with drag and drop and default file association (when it's built)
> add file argument

- BasementRenovator.py
- README.md
It was already doing this for icons, but now it basically sets up a drop
in basementrenovator folder
Also fix autogen tab Pickup > Pickups
> make autogen output EntitiesMod.xml into ModTemp

- BasementRenovator.py
- NicheFeatures.md
- resources/EntitiesAfterbirthPlus.xml
All the current mirrored entities were hard coded, they are now read
from the xml
> add support for custom mirrored entities

- BasementRenovator.py
switch to using the game's system of a flat array of grids
fix all out of bounds entity issues
fix weird placement issues in oddly shaped rooms
enhance the room system to work with a better representation of each
room shape; this is most felt on L rooms and closets
enhance visual wall snap, out of bounds detection, grid display, entity
painting with the new room info
switch some of the older settings to use the newer system (Grid,
StatusBar, Bitfont)
fix stage replcament tests after the change to permissive file names
> overhaul coordinate system to use grid indices

- BasementRenovator.py
- NicheFeatures.md
> fix null/empty room and weight filters

- BasementRenovator.py
- resources/modtemplate/main.lua
When replacing stage, give dad's key, debug 8, reseed the floor
until it contains the room being tested, and enable all doors
Add a display for the room file being tested
Fix a bug where room weight wouldn't update
Fix an oversight where changing a room name wouldn't dirty
Fix issue where rooms rendered 1 square smaller all around
Add setting to enable/disable out of bounds grids, default to false,
default snap to bounds on
Completely invalid entity locations are now logged and discarded
Fix bug with saving to an empty room filename
> add more features to stage replacement

- BasementRenovator.py
- resources/Old Scripts/text-rooms-examples.txt
> add text file compatibility

- BasementRenovator.py
Profiled comparison using cProfile:
caves.stb (base game, 951 rooms)
Before: 4.654s
After: 0.613s
7.6x speedup
Optimizations:
- preallocate a buffer to store the data in (biggest win)
- precompile all the byte packers that can be
- cache number of spawns
Remaining bottlenecks:
- Iteration. Thanks python!!!!
> speed up saving rooms

- BasementRenovator.py
- resources/modtemplate/main.lua
allow running a series of console commands at the start of a test run
fix right + left click bug
paste now selects the pasted entities
debug room printing includes room names
add fallback question mark icon for non-autogen mod entities
> add test configuration

- BasementRenovator.py
> add copy screenshot to clipboard option

- BasementRenovator.py
- src/core.py
- src/roomconvert.py
Can now save and load from xml
Add Export to STB option for final saves
XML serialization is on-par with STB's speed, shouldn't be a noticable
change. Should be even faster once core types have proper integration
Moved serialization/deserialization logic into roomconvert module
Introduced common core data format; integration into BR at large later
Remove redundant xml code
> change BR's default file format to xml

- src/roomconvert.py
Antibirth uses the afterbirth format in most places, but occasionally it uses
a modified version of it with 9 extra bytes in the room header.
In all the files I looked at, this was unused, but it may be more clear
in rep. I don't have the anti entities xml or anything so that will
rely on someone else making it.
> antibirth stb compatibility

- resources/EntitiesAntibirth.xml
No icons, but this is all the unique anti entities, grouped roughly
> add anti entities xml

- BasementRenovator.py
Dragging a file into BR will now open it
> add file drag drop

- BasementRenovator.py
To avoid confusion, opening stbs is now called "import" (txt also uses
this)
Any type of file opening will immediately save an xml copy
Only xml files will be added to the recent files list
Add an option to export to stb on save
Rename room Export -> Copy to File since that option already confused
people
Fix drag drop multiple files onto BR
> separate stb/xml opening workflow

- BasementRenovator.py
- src/roomconvert.py
Need to escape various characters to successfully load them
Fix title path updates when importing
Fix import crash from invalid param
> fix name encoding for xml files

- BasementRenovator.py
- src/roomconvert.py
handle invalid room shapes when loading xml
fix how effects are handled by autogen
> sort doors on save for source control friendliness

- BasementRenovator.py
- resources/EntitiesAntibirth.xml
give nightwatch's subtypes better names
make exe tests not block BR's thread
> load anti entities on launch if in anti mode

- BasementRenovator.py
- resources/EntitiesAfterbirthPlus.xml
optimize door creation on room load by caching images
stop re-caching door info when switching rooms
- Door updates already directly update the cache
fix stage path matches to only include filename
> add a dialog when importing over an existing xml

- .github/workflows/pyinstaller_win.yml
Oops
(you should probably cancel the action that will inevitably run btw)
> Only run release generation on main branch

- BasementRenovator.py
- src/constants.py
> Added Fissure spawner Dial input and tooltips

- BasementRenovator.py
- resources/EntitiesRepentance.xml
Also fixes the Ultra Greed Door entity not having a name, which caused a crash with search.
> Fix search tab not containing any entities

- src/bulk-entity-replacer.py
Now uses the config file's directory as the working directory for loading files, enabling drag and drop and non-absolute paths.
Can also now load directories recursively, and stb argument can be set in config json rather than as a command line argument if desired.
> Improve Bulk Entity Replacer

- .gitignore
- BasementRenovator.py
- resources/modtemplate/main.lua
Increased timeout and use abs path on test hooks to match save hooks, fix global variable in fireCallback, add VS Code Workspace to gitignore.
> Minor Test Fixes

- resources/EntitiesRebirth.xml
- resources/RoomTypesAntibirth.xml
Buttlicker has 3 rooms only in caves / flooded caves vs 62 in catacombs. Leech was listed in utero, but appears even more often in womb / scarred womb.
> move leech > shared ch3, buttlicker > catacombs

- resources/StagesRepentance.xml
Stage 9c takes you to Ascent which lets Ascent layouts be loaded with goto
> Ascent now works with multi-room testing

- BasementRenovator.py
- README.md
- resources/EntitiesAfterbirth.xml
- resources/EntitiesAfterbirthPlus.xml
- resources/EntitiesRebirth.xml
- resources/EntitiesRepentance.xml
- src/core.py
- src/lookup.py
-Also reorganized enemies in Ascent
-Also added Level 2 Charger to Ascent and Begotten to Gehenna
> Added StageHP+Armor to entity info display

- README.md
- README_zh.md
I translated the README file into Chinese and added a link in the README to the translated version.
> Add README_zh.md
